// Auto-generated by research-agent.js
// Last updated: 2026-05-22T14:02:03.064Z

window.MARKET_DATA = {
  "lastUpdated": "2026-05-22T14:02:03.063Z",
  "lastUpdatedReadable": "Friday, May 22, 2026",
  "trends": {
    "trends": []
  },
  "auctions": {
    "auctions": []
  },
  "competitors": {
    "competitors": [],
    "feature_matrix": []
  }
};
