// Auto-generated by research-agent.js
// Last updated: 2026-04-24T10:42:24.144Z

window.MARKET_DATA = {
  "lastUpdated": "2026-04-24T10:42:24.143Z",
  "lastUpdatedReadable": "Friday, April 24, 2026",
  "trends": {
    "trends": [
      {
        "make": "Ferrari",
        "model_segment": "Halo Hypercars (288 GTO / Enzo / F40 / F50 / LaFerrari)",
        "signal": "Hagerty Supercar Index surged 19% in Q1 2026, led by the Ferrari 288 GTO (+106%) and Enzo (+109%) following record-smashing Mecum Kissimmee results.",
        "direction": "up",
        "source": "hagerty.com",
        "date": "2026-04-24",
        "summary": "The Hagerty Supercar Index, which tracks 15 collectible modern supercars, surged 19% in the first quarter of 2026, largely driven by explosive gains in Ferrari halo cars. At Mecum Kissimmee 2026, the Bachmann Collection produced an $8.525M 288 GTO and an $11.11M Enzo, while a 1962 Ferrari 250 GTO 'Bianco Speciale' sold for $38.5M. Ferrari occupies nine of the top ten auction results in the first quarter of 2026, and the F50 and Porsche Carrera GT also gained 50% and 55% respectively during the same period."
      },
      {
        "make": "Ferrari",
        "model_segment": "Mid-Engine V8 (458 / F355 / 360)",
        "signal": "Ferrari 458, F355, and 360 models are appreciating or holding firm in 2026 after a post-pandemic correction, while newer models like the 296 and SF90 continue to depreciate heavily.",
        "direction": "up",
        "source": "accio.com",
        "date": "2026-04-10",
        "summary": "The mid-engine Ferrari market in 2026 shows a clear split: classic and early-modern models (F355, 360, 458) are demonstrating price strength and appreciation, while the 296 and SF90 face annual depreciation of nearly 20%. The 458 Speciale in particular remains a strong investment candidate, with prices recovering strongly from pandemic-era corrections. Buyers are increasingly informed and selective, favoring original, unmodified examples."
      },
      {
        "make": "Porsche",
        "model_segment": "Carrera GT (2004–2007)",
        "signal": "The Porsche Carrera GT was named to Hagerty's 2026 Bull Market List with values around $1.5M and climbing again after a brief plateau, up ~55% in Q1 2026 per the Hagerty Supercar Index.",
        "direction": "up",
        "source": "hagerty.com",
        "date": "2026-04-24",
        "summary": "Hagerty placed the Carrera GT on its 2026 Bull Market List, citing only 1,270 units produced, renewed collector enthusiasm for analog hypercars, and values of approximately $1.5 million that have resumed an upward trajectory. The Supercar Index confirms the model gained 55% in Q1 2026. Porsche Classic operations in Atlanta are actively involved in recommissioning projects for Carrera GT owners, reinforcing the model's blue-chip status."
      },
      {
        "make": "Lamborghini",
        "model_segment": "Miura P400 / SV",
        "signal": "A 1970 Lamborghini Miura P400 fetched $1.705M at Mecum Glendale in March 2026, and the SV sub-segment is seeing consistent results in the $3.5M–$4.5M range, boosted by the model's 60th anniversary celebrations.",
        "direction": "up",
        "source": "dupontregistry.com",
        "date": "2026-03-21",
        "summary": "The Lamborghini Miura market is experiencing a renaissance in 2026, coinciding with the model's 60th anniversary and a dedicated 'Born Incomparable' exhibition at Lamborghini's Sant'Agata Bolognese headquarters. A verde Miura P400 (one of six in that color) fetched $1.705M at Mecum Glendale, and recent Miura SV results have clustered between $3.5M and $4.5M, with a low-mileage SV consigned to Mecum Indy in May expected to push that ceiling further. The Hagerty Blue Chip Index also noted an 18% gain for the Miura P400 SV this quarter."
      },
      {
        "make": "McLaren",
        "model_segment": "F1 Road Car / Racing Provenance",
        "signal": "A 1994 McLaren F1 road car set an all-time model auction record of $25.3M at RM Sotheby's Abu Dhabi in December 2025, underpinning continued strength in McLaren F1 collectibles heading into 2026.",
        "direction": "up",
        "source": "motorsportmagazine.com",
        "date": "2025-12-10",
        "summary": "McLaren's championship double in 2025 (its first since 1998) has dramatically elevated collector interest across all McLaren road and race cars. The 1994 McLaren F1 road car sold for $25.3M at RM Sotheby's Abu Dhabi, while the unraced 2026 MCL40A F1 chassis sold for $11.48M in a world-first pre-season auction. The McLaren brand's collectible halo effect is at a multi-decade high, with younger collectors driving demand for championship-winning provenance."
      },
      {
        "make": "BMW",
        "model_segment": "E30 M3 (1987–1991)",
        "signal": "The E30 M3 marks its 40th anniversary in 2026, with well-maintained US examples trading at $45,000–$75,000 and rare Sport Evolution variants (only 600 built) pushing well past $100,000; the model holds a stable-to-rising trajectory.",
        "direction": "up",
        "source": "bmwblog.com",
        "date": "2026-01-29",
        "summary": "The BMW E30 M3 celebrates its 40th anniversary in 2026, with BMW planning a significant presence at the Goodwood Festival of Speed. Classic.com data shows the average E30 M3 sale price at approximately $87,047, with Sport Evolution examples at $165,000+ per Hagerty's valuation tool. Prices reflect genuine scarcity and cultural cachet rather than speculation, and the model is increasingly recognized as a design and motorsport artifact on par with Italian contemporaries."
      },
      {
        "make": "Mercedes-Benz",
        "model_segment": "W113 Pagoda SL (230/250/280SL)",
        "signal": "The Hagerty German Car Index softened slightly in Q1 2026 amid broader macro headwinds and tariff concerns for imported European cars, though blue-chip Pagoda examples remain resilient with average 280SL values around £70,560.",
        "direction": "stable",
        "source": "hagerty.com",
        "date": "2026-04-24",
        "summary": "The Hagerty index of German cars was among the four indexes that moved down in the Q1 2026 report, reflecting broader economic softness and tariff-related uncertainty weighing on imported collectibles in the US market. However, top-tier W113 Pagoda SLs remain strong, with the classicvaluer.com guide showing average 280SL values around £70,560 and a historic high of £265,013 for the finest examples. The bifurcation between blue-chip originals and average-condition cars continues to widen."
      },
      {
        "make": "Ferrari / Broad Market",
        "model_segment": "Overall Collector Car Market (Hagerty Market Rating)",
        "signal": "The Hagerty Market Rating slipped 0.11 points to 58.9 in April 2026 amid 0.9% monthly inflation—the highest single-month reading since summer 2022—keeping the index in 'flat market' territory for 15 consecutive months.",
        "direction": "stable",
        "source": "hagerty.com",
        "date": "2026-04-23",
        "summary": "The April 2026 Hagerty Market Rating of 58.9 reflects a two-tier market: top-end supercars and hypercars continue to attract ultra-wealthy buyers and set records, while mid-tier and lower-value collector cars face persistent softness—only 35.2% of private transactions are selling above insured value, the second-lowest ratio in over four years. Tariffs are adding to maintenance costs for imported European cars, and Hagerty analysts caution that big top-end auction results can create a misleading picture of overall market health. The next major test for the market will be Mecum Indy in May 2026."
      }
    ]
  },
  "auctions": {
    "auctions": [
      {
        "house": "Barrett-Jackson",
        "car": "2016 Pagani Huayra",
        "result": "$3,190,000",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-18",
        "source_url": "https://news.dupontregistry.com/blogs/auctions/barrett-jackson-2026-palm-beach-auction-top-10-results-highlights",
        "source_domain": "dupontregistry.com",
        "summary": "One of only 100 produced, this Gray Clement/blue carbon fiber Huayra with 2,331 miles set an all-time Palm Beach auction record and exceeded its Hagerty dRi value of ~$2.5M. Sold without reserve at the South Florida Fairgrounds."
      },
      {
        "house": "Barrett-Jackson",
        "car": "2025 Ferrari SF90 XX Stradale",
        "result": "$1,870,000",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-18",
        "source_url": "https://journal.classiccars.com/2026/04/21/barrett-jackson-celebrates-palm-beach-auctions-history-making-vehicle-sales/",
        "source_domain": "classiccars.com",
        "summary": "A Bianco Artico example with only 212 miles, featuring airbrushed Scuderia shields and a Giallo Modena racing stripe. Became the second-highest result in Palm Beach auction history, sold without reserve."
      },
      {
        "house": "Barrett-Jackson",
        "car": "2024 Porsche 911 S/T",
        "result": "$665,500",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-17",
        "source_url": "https://news.dupontregistry.com/blogs/auctions/barrett-jackson-2026-palm-beach-auction-top-10-results-highlights",
        "source_domain": "dupontregistry.com",
        "summary": "One of just 1,963 examples of the limited-production air-cooled tribute 911 S/T, sold at the Palm Beach 2026 auction without reserve. Three 911 GT3 RS Weissach examples also traded between $385,000–$495,000 at the same event."
      },
      {
        "house": "Barrett-Jackson",
        "car": "1979 Ferrari 308 GTS Targa (ex-Magnum P.I.)",
        "result": "$379,000",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-17",
        "source_url": "https://www.classic-car-auctions.info/usa/florida/2026-barrett-jackson-palm-beach-sale-auction-results/",
        "source_domain": "classic-car-auctions.info",
        "summary": "The Targa driven by Tom Selleck in the pilot episode and first season of Magnum P.I. in the early 1980s. A stark premium over comparable 308s sold without celebrity provenance — a standard 308 GTS Targa brought only $58,300 at Scottsdale in January."
      },
      {
        "house": "Broad Arrow",
        "car": "2005 Porsche Carrera GT (Gulf Blue, Paint-to-Sample)",
        "result": "$6,715,000",
        "result_vs_estimate": "above",
        "date": "2026-03-07",
        "source_url": "https://www.classic-car-auctions.info/usa/florida/amelia-island/2026-broad-arrow-amelia-island-sale-top-auction-results/",
        "source_domain": "classic-car-auctions.info",
        "summary": "The only Carrera GT ever specified in Gulf Blue, with 2,807 miles, obliterated the prior model record of $3,305,000 set just one week earlier at RM Sotheby's Miami. More than ten new world records were set at Broad Arrow's most successful Amelia Island sale ever, totaling $111M."
      },
      {
        "house": "Broad Arrow",
        "car": "1972 Lamborghini Miura P400 SV",
        "result": "$6,700,000",
        "result_vs_estimate": "above",
        "date": "2026-03-07",
        "source_url": "https://www.hagerty.com/media/market-trends/hagerty-insider/modern-hypercars-sizzle-at-the-2026-march-auctions-full-results-and-analysis/",
        "source_domain": "hagerty.com",
        "summary": "Set a new model record for the Miura SV despite less-than-perfect condition, underscoring surging demand for blue-chip Italian classics at Amelia Island 2026. The result came alongside a record Porsche Carrera GT and Ferrari Monza SP2 at the same sale."
      },
      {
        "house": "Broad Arrow",
        "car": "2021 Ferrari Monza SP2",
        "result": "$4,955,000",
        "result_vs_estimate": "above",
        "date": "2026-03-07",
        "source_url": "https://www.classic-car-auctions.info/usa/florida/amelia-island/2026-broad-arrow-amelia-island-sale-top-auction-results/",
        "source_domain": "classic-car-auctions.info",
        "summary": "A new model record at over double the original list price and more than $1M above the previous record holder. This American-delivery example showed only 16 miles and was one of 499 Icona series cars produced."
      },
      {
        "house": "Bonhams",
        "car": "2019 Lamborghini Aventador SVJ Coupé",
        "result": "TBD (Est. €520,000–€620,000)",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-24",
        "source_url": "https://cars.bonhams.com/auction/31711/the-monaco-sale/",
        "source_domain": "cars.bonhams.com",
        "summary": "Offered at the Bonhams Monaco Sale at the Fairmont Hotel on April 24, coinciding with the Grand Prix de Monaco Historique weekend. Results not yet published as of April 24, 2026."
      },
      {
        "house": "RM Sotheby's",
        "car": "2014 Ferrari LaFerrari (ex-Jay Kay, Signal Green)",
        "result": "TBD (Est. €4,000,000–€4,500,000)",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-25",
        "source_url": "https://rmsothebys.com/auctions/mc26/lots/r0025-2014-ferrari-laferrari/",
        "source_domain": "rmsothebys.com",
        "summary": "The only LaFerrari finished in Extra Campionario Signal Green, originally owned by Jamiroquai frontman Jay Kay and one of only 50 with an exposed carbon fibre roof. Offered at the biennial RM Sotheby's Monaco sale at the Grimaldi Forum on April 25 — results pending."
      },
      {
        "house": "RM Sotheby's",
        "car": "2004 Ferrari Enzo (Argento Nürburgring)",
        "result": "TBD (Est. €4,900,000–€5,300,000)",
        "result_vs_estimate": "no reserve",
        "date": "2026-04-25",
        "source_url": "https://rmsothebys.com/auctions/mc26/lots/r0007-2004-ferrari-enzo/",
        "source_domain": "rmsothebys.com",
        "summary": "One of only nine Enzos finished in Argento Nürburgring and the only one delivered to the UK, with Ferrari Classiche 'Red Book' certification and 19,079 km on the clock. Offered at RM Sotheby's Monaco 2026 — results pending as of April 24."
      }
    ]
  },
  "competitors": {
    "competitors": [
      {
        "name": "MyCollection.world",
        "recent_headline": "No major funding or product launch news detected in the past 60 days; platform continues to develop AI-assisted document management, expense tracking, 3D digital twin experiences, and European market-price valuation for classic and supercar collectors.",
        "news_items": [
          {
            "title": "MyCollection.world Platform Feature Profile (Current)",
            "date": "2026-04-24",
            "source": "mycollection.world",
            "summary": "MyCollection.world is a comprehensive digital assistant for classic and supercar collectors offering AI-driven document classification, expense and maintenance tracking, market-price updates from Europe's leading price database, and immersive 3D/digital twin vehicle experiences. No recent funding, partnership, or pricing-change announcements were found in the past 60 days."
          }
        ],
        "threat_level": "medium",
        "threat_rationale": "MyCollection.world directly targets the same HNW classic/supercar collector niche as Driver's Paddock with an overlapping feature set including AI automation, document management, and market valuation, but appears limited to a European price database and lacks confirmed insurance, auction, or broad marketplace integrations.",
        "dp_advantage": "Driver's Paddock can differentiate through deeper concierge-level service, broader global valuation coverage beyond Europe, and tighter integration with insurance and auction partner ecosystems unavailable on MyCollection.world."
      },
      {
        "name": "Hagerty",
        "recent_headline": "Hagerty reported record 2025 results with 17% revenue growth and 91% net income surge, launched a Prime Video FAST channel in February 2026, set a $111M auction record at Amelia Concours via Broad Arrow in March 2026, and is guiding for 15–16% written premium growth in 2026 backed by its Markel fronting deal and State Farm expansion to 27 states.",
        "news_items": [
          {
            "title": "Hagerty Reports Full Year 2025 Results; Provides 2026 Growth Outlook",
            "date": "2026-02-26",
            "source": "prnewswire.com",
            "summary": "Hagerty posted 17% top-line growth and a 91% net income surge in 2025, added 371,000 new members, launched Enthusiast+, expanded State Farm Classic+ to 27 states, and renegotiated the Markel fronting arrangement to capture 100% of premiums — guiding for 15–16% written premium growth and further margin expansion in 2026."
          },
          {
            "title": "Hagerty Channel Debuts on Prime Video",
            "date": "2026-02-09",
            "source": "prnewswire.com",
            "summary": "Hagerty launched a free ad-supported (FAST) streaming channel on Amazon Prime Video delivering 24/7 original automotive enthusiast content, deepening brand reach and member engagement across thousands of compatible devices."
          },
          {
            "title": "Broad Arrow Realizes Most Successful Auction in Amelia Car Week History with $111 Million in Total Sales",
            "date": "2026-03-09",
            "source": "globenewswire.com",
            "summary": "Hagerty's Broad Arrow Auctions achieved over $111M at the 2026 Amelia Concours Auction — the highest-grossing sale in the event's 31-year history — with a 92% sell-through rate, 1,000+ bidders from 23 countries, and 13 new world auction records including a $15,185,000 Ferrari Enzo."
          },
          {
            "title": "Hagerty Enthusiast Plus Launches on Duck Creek Platform",
            "date": "2026-02-26",
            "source": "investing.com",
            "summary": "Hagerty's technology teams are migrating to a modern cloud-based architecture and have launched Enthusiast Plus on Duck Creek to target growing demand from younger generations of car enthusiasts, signaling a push to expand beyond the core classic-car audience."
          }
        ],
        "threat_level": "high",
        "threat_rationale": "Hagerty is an at-scale, publicly traded competitor with 2.7M insured vehicles, a dominant specialty insurance position, a fast-growing auction house (Broad Arrow), a streaming media channel, a 371K-member growth engine, and aggressive 2026 expansion plans — all targeting the same HNW collector audience as Driver's Paddock.",
        "dp_advantage": "Driver's Paddock can win on white-glove portfolio management depth, multi-asset (not just automotive) collection oversight, and privacy-first HNW concierge experiences that Hagerty's mass-market membership model cannot replicate."
      },
      {
        "name": "Carfax",
        "recent_headline": "Carfax launched VIN-specific 'Future Reliability' predictions on April 7, 2026 — an industry first using 35 billion records — and reported used car prices spiked $1,500 in one month to ~$25,500 average amid tariff-driven market disruption.",
        "news_items": [
          {
            "title": "CARFAX Report Now Delivers Future Reliability Based on a Vehicle's Unique VIN-Specific History",
            "date": "2026-04-07",
            "source": "prnewswire.com",
            "summary": "Carfax launched Future Reliability, a VIN-specific predictive feature built on 151,000+ data sources and 35 billion records, allowing shoppers and owners to anticipate repairs and costs for an individual vehicle — an industry first that now appears in a redesigned Past/Present/Future report header."
          },
          {
            "title": "CARFAX: Used Car Prices Spike After Hitting 12-Month Low",
            "date": "2026-04-14",
            "source": "prnewswire.com",
            "summary": "Carfax data shows the average used vehicle price jumped ~$1,500 in one month to ~$25,500, driven by tariff-related new-model price increases, tighter used-car supply, and a surge in EV prices of $560+, reinforcing Carfax's role as the leading public data authority on used-vehicle market trends."
          },
          {
            "title": "Carfax Adds Future Reliability — Vehicle Lifespan Insights Coming Next",
            "date": "2026-04-07",
            "source": "autoremarketing.com",
            "summary": "Carfax confirmed that vehicle lifespan prediction will be the next feature added to Future Reliability, further expanding its analytics roadmap beyond historical ownership and damage data into forward-looking AI-driven insights."
          }
        ],
        "threat_level": "low",
        "threat_rationale": "Carfax competes primarily in the mass-market used-car transaction and history-report space, not in luxury collection portfolio management, and its new Future Reliability feature targets everyday car buyers and dealers rather than HNW multi-vehicle collectors.",
        "dp_advantage": "Driver's Paddock serves collectors who already know their vehicles' provenance intimately and require sophisticated portfolio analytics, insurance optimization, and concierge services that Carfax's transaction-oriented, consumer-grade reports do not address."
      }
    ],
    "feature_matrix": [
      {
        "feature": "Portfolio valuation / market pricing",
        "dp": true,
        "mycollection": true,
        "hagerty": true,
        "carfax": true
      },
      {
        "feature": "Document & provenance management",
        "dp": true,
        "mycollection": true,
        "hagerty": false,
        "carfax": false
      },
      {
        "feature": "Specialty / agreed-value insurance",
        "dp": false,
        "mycollection": false,
        "hagerty": true,
        "carfax": false
      },
      {
        "feature": "AI-driven collection management automation",
        "dp": true,
        "mycollection": true,
        "hagerty": false,
        "carfax": false
      },
      {
        "feature": "Live auction / marketplace access",
        "dp": false,
        "mycollection": false,
        "hagerty": true,
        "carfax": false
      },
      {
        "feature": "VIN-level vehicle history reporting",
        "dp": false,
        "mycollection": false,
        "hagerty": false,
        "carfax": true
      },
      {
        "feature": "3D digital twin / immersive vehicle experience",
        "dp": false,
        "mycollection": true,
        "hagerty": false,
        "carfax": false
      },
      {
        "feature": "HNW concierge / white-glove service model",
        "dp": true,
        "mycollection": false,
        "hagerty": false,
        "carfax": false
      }
    ]
  }
};
